# Site
name: "doloresğŸ¥€"
title: "drifted"
description: "é…”ã¤ã¦ã‹ã‚‰å’„ã‚‚å…«é‡ã®æ¡œå“‰"
logo: 'assets/images/lamp.png'
favicon: 'assets/images/miffy.png'
baseurl: ""
google_analytics: 'G-M6WJDTX8XM'
disqus: 'dolores824'
# mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/
email: dolores.tan@pm.me

# Authors
authors:
  # sal:
  #   name: Sal
  #   display_name: Sal
  #   avatar: 'assets/images/avatar-sal.png'
  #   email: wowthemesnet@gmail.com
  #   web: https://www.wowthemes.net/donate/
  #   twitter: https://twitter.com/wowthemesnet
  #   description: "Author of Memoirs, a Bootstrap Medium styled template available for Jekyll. You are currently previewing Jekyll template demo."
  # john:
  #   name: John
  #   display_name: John    
  #   avatar: 'assets/images/avatar.png'
  #   email: wowthemesnet@gmail.com
  #   web: https://www.wowthemes.net
  #   twitter: https://twitter.com/wowthemesnet
  #   description: "Write a short description of the author here. You are currently previewing Memoirs demo, a Jekyll template compatible with Github pages."
  Dolores:
    name: Dolores
    display_name: Dolores    
    avatar: 'assets/images/nara.png'
    email: dolores.tan@pm.me
    web: https://dolores824.github.io
    description: "èŸ¾èœè¢«æ¡ƒèŠ±é¦™æ°”æ‰€è¯±"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
  - jekyll-stickyposts
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 9
paginate_path: /page:num/
    
# Other
highlighter: rouge
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]

# stickyposts
stickyposts:
  enabled: true    # Enable StickyPosts; default: true